# Generated by Django 4.0.2 on 2022-03-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicoglobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaGeneral',
            fields=[
                ('pege_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pege_tipopersona', models.IntegerField(blank=True, null=True)),
                ('pege_direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('pege_mail', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"general"."personageneral"',
                'managed': False,
            },
        ),
    ]
