# Generated by Django 4.0.2 on 2022-03-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicoglobal', '0002_personageneral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonaGeneral',
        ),
    ]
