# Generated by Django 4.0.2 on 2022-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0002_proyectosproyeccionsocial_total_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='docenteExterno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('doc_identidad', models.CharField(max_length=15, verbose_name='Documento')),
                ('pri_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sec_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('pri_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('sec_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('institucion', models.CharField(max_length=80, verbose_name='Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='estudianteExterno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('doc_identidad', models.CharField(max_length=15, verbose_name='Documento')),
                ('pri_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sec_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('pri_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('sec_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('institucion', models.CharField(max_length=80, verbose_name='Institucion')),
            ],
        ),
    ]
