# Generated by Django 4.0.2 on 2022-03-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('fecha', models.DateField(auto_now_add=True, max_length=15, verbose_name='Fecha')),
                ('documento', models.CharField(max_length=30, verbose_name='Cc Estudiante')),
                ('convenio', models.CharField(max_length=30, verbose_name='Numero Convenio')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre Estudiante')),
                ('telefono', models.CharField(max_length=15, verbose_name='Celular Estudiante')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('programa', models.CharField(choices=[('Regionalizacion', 'Regionalizacion'), ('UT Solidaria', 'UT Solidaria'), ('UT Para los niños', 'UT Para los niños'), ('UT En tu comunidad', 'UT En tu comunidad'), ('Articulacion con la escuela', 'Articulacion con la escuela'), ('Universidad territorio de paz', 'Universidad territorio de paz'), ('Apropiacion social del conocimiento', 'Apropiacion social del conocimiento'), ('Universidad abierta', 'Universidad abierta')], max_length=50, verbose_name='Programa')),
                ('facultad', models.CharField(choices=[('No aplica', 'No aplica'), ('Facultad de ciencias humanas y artes', 'Facultad de ciencias humanas y artes'), ('Facultad de ciencias de la educacion', 'Facultad de ciencias de la educacion'), ('Facultad de medicina veterinaria', 'Facultad de medicina veterinaria'), ('Facultad de ciencias basicas', 'Facultada de ciencias basicas'), ('Facultad de tecnologia', 'Facultad de tecnologia'), ('IDEAD', 'IDEAD'), ('Facultad de ingenieria agronomica', 'Facultad de ingenieria agronomica'), ('Facultad de ingenieria forestal', 'Facultad de ingenieria forestal'), ('Facultad de ciencias en la salud', 'Facultad de ciencias en la salud')], max_length=80, verbose_name='Facultad')),
            ],
            options={
                'verbose_name_plural': 'Convenios',
            },
        ),
        migrations.CreateModel(
            name='ProyectosProyeccionSocial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('fecha', models.DateField(auto_now_add=True, max_length=15, verbose_name='Fecha')),
                ('programa', models.CharField(choices=[('Regionalizacion', 'Regionalizacion'), ('UT Solidaria', 'UT Solidaria'), ('UT Para los niños', 'UT Para los niños'), ('UT En tu comunidad', 'UT En tu comunidad'), ('Articulacion con la escuela', 'Articulacion con la escuela'), ('Universidad territorio de paz', 'Universidad territorio de paz'), ('Apropiacion social del conocimiento', 'Apropiacion social del conocimiento'), ('Universidad abierta', 'Universidad abierta')], max_length=50, verbose_name='Programa')),
                ('sub_proyecto', models.CharField(blank=True, max_length=150, null=True, verbose_name='SubProyecto')),
                ('ciudad', models.CharField(choices=[('Ibague', 'Ibague'), ('Bogota', 'Bogota')], max_length=30, verbose_name='Ciudad')),
                ('institucion', models.CharField(max_length=30, verbose_name='Nombre de la institucion')),
                ('codigoBput', models.CharField(default=0, max_length=50, verbose_name='Codigo BPUT')),
                ('evidencia', models.ImageField(null=True, upload_to='Evidencias')),
                ('nombreDocente', models.CharField(default='Nn', max_length=50, verbose_name='Nombre del docente')),
                ('numeroEstudiantes', models.IntegerField(default=0, verbose_name='Numero de estudiantes')),
                ('tipoComunidad', models.CharField(choices=[('No aplica', 'No aplica'), ('Indigena', 'Indigena'), ('Afrodecendiente', 'Afrodecendiente'), ('Campesino', 'Campesino'), ('Comunidad LGBTI', 'Comunidad LGBTI'), ('Victima del conflicto armado', 'Victima del conflicto armado')], default='Nn', max_length=30, verbose_name='Tipo de Comunidad')),
                ('organizacion', models.CharField(default='Nn', max_length=30, verbose_name='Organizacion')),
                ('facultad', models.CharField(choices=[('No aplica', 'No aplica'), ('Facultad de ciencias humanas y artes', 'Facultad de ciencias humanas y artes'), ('Facultad de ciencias de la educacion', 'Facultad de ciencias de la educacion'), ('Facultad de medicina veterinaria', 'Facultad de medicina veterinaria'), ('Facultad de ciencias basicas', 'Facultad de ciencias basicas'), ('Facultad de tecnologia', 'Facultad de tecnologia'), ('IDEAD', 'IDEAD'), ('Facultad de ingenieria agronomica', 'Facultad de ingenieria agronomica'), ('Facultad de ingenieria forestal', 'Facultad de ingenieria forestal'), ('Facultad de ciencias en la salud', 'Facultad de ciencias en la salud')], default='Nn', max_length=80, verbose_name='Facultad')),
                ('nombreProyecto', models.CharField(default='Nn', max_length=50, verbose_name='Nombre del proyecto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
    ]
