# Generated by Django 4.0.2 on 2022-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0002_alter_convenios_options_alter_convenios_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosProyeccionSocial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('fecha', models.DateField(auto_now_add=True, max_length=15, verbose_name='Fecha')),
                ('programa', models.CharField(choices=[('Regionalizacion', 'Regionalizacion'), ('UT Solidaria', 'UT Solidaria'), ('UT Para los niños', 'UT Para los niños'), ('UT En tu comunidad', 'UT En tu comunidad'), ('Articulacion con la escuela', 'Articulacion con la escuela'), ('Universidad territorio de paz', 'Universidad territorio de paz'), ('Apropiacion socail del conocimiento', 'Apropiacion socail del conocimiento'), ('Universidad abierta', 'Universidad abierta')], max_length=50, verbose_name='Programa')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('institucion', models.CharField(max_length=30, verbose_name='Numero Convenio')),
                ('numeroEstudiantes', models.IntegerField(verbose_name='Numero de estudiantes')),
                ('tipoComunidad', models.CharField(choices=[('No aplica', 'No aplica'), ('Indigena', 'Indigena'), ('Afrodecendiente', 'Afrodecendiente'), ('Campesino', 'Campesino'), ('Comunidad LGBTI', 'Comunidad LGBTI'), ('Victima del confilto armado', 'Victima del confilto armado')], max_length=30, verbose_name='Tipo de Comunidad')),
                ('organizacion', models.CharField(max_length=30, verbose_name='Organizacion')),
                ('facultad', models.CharField(choices=[('No aplica', 'No aplica'), ('Facultad de ciencias humanas y artes', 'Facultad de ciencias humanas y artes'), ('Facultadda de ciencias de la educacion', 'Facultadda de ciencias de la educacion'), ('Facultad de medicina veterinaria', 'Facultad de medicina veterinaria'), ('Facultada de ciencias basicas', 'Facultada de ciencias basicas'), ('Facultad de tecnologia', 'Facultad de tecnologia'), ('IDEAD', 'IDEAD'), ('Facultad de ingenieria agronomica', 'Facultad de ingenieria agronomica'), ('Facultad de ingenieria forestal', 'Facultad de ingenieria forestal'), ('Facultad de ciencias en la salud', 'Facultad de ciencias en la salud')], max_length=80, verbose_name='Facultad')),
                ('nombreProyecto', models.CharField(max_length=50, verbose_name='Nombre del proyecto')),
                ('nombreDocente', models.CharField(max_length=50, verbose_name='Nombre del docente')),
                ('codigoBput', models.CharField(max_length=50, verbose_name='Codigo BPUT')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('evidencia', models.ImageField(null=True, upload_to=' Evidencias')),
            ],
            options={
                'verbose_name_plural': 'Proyectos de Proyeccion Social',
            },
        ),
        migrations.AlterField(
            model_name='convenios',
            name='facultad',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Facultad de ciencias humanas y artes', 'Facultad de ciencias humanas y artes'), ('Facultadda de ciencias de la educacion', 'Facultadda de ciencias de la educacion'), ('Facultad de medicina veterinaria', 'Facultad de medicina veterinaria'), ('Facultada de ciencias basicas', 'Facultada de ciencias basicas'), ('Facultad de tecnologia', 'Facultad de tecnologia'), ('IDEAD', 'IDEAD'), ('Facultad de ingenieria agronomica', 'Facultad de ingenieria agronomica'), ('Facultad de ingenieria forestal', 'Facultad de ingenieria forestal'), ('Facultad de ciencias en la salud', 'Facultad de ciencias en la salud')], max_length=80, verbose_name='Facultad'),
        ),
    ]
