# Generated by Django 4.0.2 on 2022-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0003_proyectosproyeccionsocial_alter_convenios_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='codigoBput',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo BPUT'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='institucion',
            field=models.CharField(max_length=30, verbose_name='Nombre de la institucion'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='nombreDocente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del docente'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='nombreProyecto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del proyecto'),
        ),
    ]
