# Generated by Django 4.0.2 on 2022-03-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0003_docenteexterno_estudianteexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='docenteE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OfConvenio.docenteexterno'),
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='estudianteE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OfConvenio.estudianteexterno'),
        ),
    ]
