# Generated by Django 4.0.2 on 2022-02-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0004_alter_proyectosproyeccionsocial_codigobput_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectosproyeccionsocial',
            options={},
        ),
    ]
