# Generated by Django 4.0.2 on 2022-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0005_alter_proyectosproyeccionsocial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='codigoBput',
            field=models.CharField(default='0', max_length=50, verbose_name='Codigo BPUT'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='nombreDocente',
            field=models.CharField(default='Nn', max_length=50, verbose_name='Nombre del docente'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='nombreProyecto',
            field=models.CharField(default='Nn', max_length=50, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='organizacion',
            field=models.CharField(default='Nn', max_length=30, verbose_name='Organizacion'),
        ),
    ]
