# Generated by Django 4.0.2 on 2022-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0007_alter_proyectosproyeccionsocial_numeroestudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='totalEstudiantes',
            field=models.IntegerField(default='0', verbose_name='Total de estudiantes'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='evidencia',
            field=models.ImageField(null=True, upload_to='Evidencias'),
        ),
    ]
