# Generated by Django 4.0.2 on 2022-02-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0011_alter_proyectosproyeccionsocial_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='ciudad',
            field=models.CharField(choices=[('Ibague', 'Ibague'), ('Bogota', 'Bogota')], max_length=30, verbose_name='Ciudad'),
        ),
    ]
