# Generated by Django 4.0.2 on 2022-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0014_alter_proyectosproyeccionsocial_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='codigoBput',
            field=models.CharField(default=0, max_length=50, verbose_name='Codigo BPUT'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
