# Generated by Django 4.0.2 on 2022-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0015_alter_proyectosproyeccionsocial_codigobput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletarProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBput', models.CharField(default=0, max_length=50, verbose_name='Codigo BPUT')),
                ('evidencia', models.ImageField(null=True, upload_to='Evidencias')),
                ('nombreDocente', models.CharField(default='Nn', max_length=50, verbose_name='Nombre del docente')),
                ('numeroEstudiantes', models.IntegerField(default=0, verbose_name='Numero de estudiantes')),
                ('tipoComunidad', models.CharField(choices=[('No aplica', 'No aplica'), ('Indigena', 'Indigena'), ('Afrodecendiente', 'Afrodecendiente'), ('Campesino', 'Campesino'), ('Comunidad LGBTI', 'Comunidad LGBTI'), ('Victima del confilto armado', 'Victima del confilto armado')], default='Nn', max_length=30, verbose_name='Tipo de Comunidad')),
                ('organizacion', models.CharField(default='Nn', max_length=30, verbose_name='Organizacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='proyectosproyeccionsocial',
            name='codigoBput',
        ),
        migrations.RemoveField(
            model_name='proyectosproyeccionsocial',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='proyectosproyeccionsocial',
            name='nombreDocente',
        ),
        migrations.RemoveField(
            model_name='proyectosproyeccionsocial',
            name='numeroEstudiantes',
        ),
        migrations.RemoveField(
            model_name='proyectosproyeccionsocial',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='proyectosproyeccionsocial',
            name='tipoComunidad',
        ),
    ]
