# Generated by Django 4.0.2 on 2022-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0016_completarproyecto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletarProyecto',
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='codigoBput',
            field=models.CharField(default=0, max_length=50, verbose_name='Codigo BPUT'),
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='evidencia',
            field=models.ImageField(null=True, upload_to='Evidencias'),
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='nombreDocente',
            field=models.CharField(default='Nn', max_length=50, verbose_name='Nombre del docente'),
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='numeroEstudiantes',
            field=models.IntegerField(default=0, verbose_name='Numero de estudiantes'),
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='organizacion',
            field=models.CharField(default='Nn', max_length=30, verbose_name='Organizacion'),
        ),
        migrations.AddField(
            model_name='proyectosproyeccionsocial',
            name='tipoComunidad',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Indigena', 'Indigena'), ('Afrodecendiente', 'Afrodecendiente'), ('Campesino', 'Campesino'), ('Comunidad LGBTI', 'Comunidad LGBTI'), ('Victima del confilto armado', 'Victima del confilto armado')], default='Nn', max_length=30, verbose_name='Tipo de Comunidad'),
        ),
    ]
