# Generated by Django 4.0.2 on 2022-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0017_delete_completarproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='facultad',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Facultad de ciencias humanas y artes', 'Facultad de ciencias humanas y artes'), ('Facultad de ciencias de la educacion', 'Facultad de ciencias de la educacion'), ('Facultad de medicina veterinaria', 'Facultad de medicina veterinaria'), ('Facultad de ciencias basicas', 'Facultada de ciencias basicas'), ('Facultad de tecnologia', 'Facultad de tecnologia'), ('IDEAD', 'IDEAD'), ('Facultad de ingenieria agronomica', 'Facultad de ingenieria agronomica'), ('Facultad de ingenieria forestal', 'Facultad de ingenieria forestal'), ('Facultad de ciencias en la salud', 'Facultad de ciencias en la salud')], max_length=80, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='programa',
            field=models.CharField(choices=[('Regionalizacion', 'Regionalizacion'), ('UT Solidaria', 'UT Solidaria'), ('UT Para los niños', 'UT Para los niños'), ('UT En tu comunidad', 'UT En tu comunidad'), ('Articulacion con la escuela', 'Articulacion con la escuela'), ('Universidad territorio de paz', 'Universidad territorio de paz'), ('Apropiacion social del conocimiento', 'Apropiacion social del conocimiento'), ('Universidad abierta', 'Universidad abierta')], max_length=50, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='proyectosproyeccionsocial',
            name='tipoComunidad',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Indigena', 'Indigena'), ('Afrodecendiente', 'Afrodecendiente'), ('Campesino', 'Campesino'), ('Comunidad LGBTI', 'Comunidad LGBTI'), ('Victima del conflicto armado', 'Victima del conflicto armado')], default='Nn', max_length=30, verbose_name='Tipo de Comunidad'),
        ),
    ]
