# Generated by Django 4.0.2 on 2022-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfConvenio', '0018_alter_convenios_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='programa',
            field=models.CharField(choices=[('Regionalizacion', 'Regionalizacion'), ('UT Solidaria', 'UT Solidaria'), ('UT Para los niños', 'UT Para los niños'), ('UT En tu comunidad', 'UT En tu comunidad'), ('Articulacion con la escuela', 'Articulacion con la escuela'), ('Universidad territorio de paz', 'Universidad territorio de paz'), ('Apropiacion social del conocimiento', 'Apropiacion social del conocimiento'), ('Universidad abierta', 'Universidad abierta')], max_length=50, verbose_name='Programa'),
        ),
    ]
